### PR TITLE
Updated to Swift 4/Xcode 9

### LINKED ISSUE #1: Do you have plan to update to Swift 3?
Hi, do you have plan to update this framework to Swift 3?

### PR DESCRIPTION
**Pull request by danspndl**
- Upgraded the project to Swift 4/Xcode 9 and cleaned up a few things
- Added a few more tests
- Renamed `iCal` enum to `iCalManager` to avoid ambiguous error from Xcode
- I've added a few TODO marks to add documentation or to fix minor issues. I'll fix them later
- Fixed #1

### CODE REVIEW

**Comment by kiliankoe** [comment]
Hey, sorry about getting back to you so late! Huge thanks for updating the project to current Swift and the rest of the fixes/patches 🎉 

If I could just ask you for one more change removing all the `// End {class, extension, struct, ...}` comments, that would be great, thanks! 😊

**Comment by danspndl** [comment]
Sure, sorry about that. :) I'll try to clean it up a bit more and implement a few more things later. If you have any ideas, just open an issue and I'll take a look ;)

**Comment by kiliankoe** [comment]
Awesome, thank you! 😊 

Just out of curiosity, are you using this library for something? I had the need at one point a year back and started with this, but never actually got around to using it 🙈

**Comment by kiliankoe** [comment]
I also just invited you as a collaborator 😊

**Comment by danspndl** [comment]
Thanks! Yes, I'd like to use it for my project. I hope I'll have enough time before university to implement it. :)

**Pull request merged**
